contact/urls.py
from . import views
from django.urls import path
app_name = 'contact'


urlpatterns = [

    
   path('contact/',views.sendmail,name="sendmail"),
   path('success/',views.success,name="success"),
 
   
]

demo/urls.py
from django.contrib import admin
from django.urls import path,include
from demoapp import views
from contact import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include("demoapp.urls" , namespace= 'demoapp.urls')),
    path('',include("contact.urls" , namespace='contact')), 
   
   
    
]


urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)   
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

demoapp/urls.py
from . import views
from django.urls import path
app_name = 'demoapp'


urlpatterns = [

    path('',views.home,name="home"),
    path('<int:tour_id>/',views.detail,name="detail"),
    path('about/',views.contact,name="contact"),
    path('travels/',views.tour_package,name="tour_package"),
 
   
]

contact/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    #location =
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return str(self.id)

demoapp/models.py
from django.db import models


# Create your models here.

class Tour(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    image = models.CharField(max_length=300)
    description = models.CharField(max_length=400)
    price = models.IntegerField()
    category = models.ForeignKey('Category' ,null=True ,on_delete=models.SET_NULL)
   

class Category(models.Model):
    category_name = models.CharField(max_length=30)
    image = models.ImageField(upload_to='demoapp/' , null=True)
    def __str__(self):
        return self.category_name
        

   
    

contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField()
    email = forms.EmailField(required=True)
    message = forms.CharField(widget=forms.Textarea ,required=True)

contact/views.py
from django.shortcuts import render,redirect
from . models import Contact
from demo.settings import EMAIL_HOST_USER
from . forms import ContactForm 
from django.core.mail import send_mail as rohit ,BadHeaderError
from django.http import HttpResponse,HttpResponseRedirect

# Create your views here.


def sendmail(request):
    
    
    if request.method == 'POST':
        
        subject = request.POST['subject']
        email = request.POST['email']
        message = request.POST['message']
            

        #try : 
        rohit(subject,
        message ,email,[EMAIL_HOST_USER],fail_silently=False )
            

        return render(request,'contact/contact.html',{'subject':subject})
        

    else: 
        return render(request,'contact/contact.html' )


def success(request):
    return render(request,'contact/success.html')

demoapp/views.py
from django.shortcuts import render
from django.template import loader
from .models import Tour

# Create your views here.
def home(request):
    
    return render(request,'demoapp/home.html')


def detail(request,tour_id):

    tour= Tour.objects.get(pk=tour_id)
    return render(request,'demoapp/detail.html',{'tour':tour})

def contact(request):
    return render(request,'demoapp/about.html')

def tour_package(request):
    tours = Tour.objects.all()

    return render(request,'demoapp/tours.html',{'tours':tours})

contact/templates/contact/contact.html
{% extends 'base.html' %}

{% block body %}
  
{% if subject %}
<center>
 <h2>
   thanks {{subject}} we will respond shortly!
 </h2>
</center>
{% else %}
  

  <section class="probootstrap-slider flexslider2 page-inner">
    <div class="overlay"></div>
    <div class="probootstrap-wrap-banner">
      <div class="container">
        <div class="row">
          <div class="col-md-8">

            <div class="page-title probootstrap-animate">
              <div class="probootstrap-breadcrumbs">
                <a href="{% url 'demoapp:home' %}">Home</a>
                <span>About</span>
              </div>
              <h1>Contact</h1>
              <br>
              <br>
            </div>

          </div>
        </div>
      </div>
    </div>

  <!-- END: slider  -->

    
  </section>
  
  
  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <h4>Send a message we'll get in Touch with you</h4>
          
          <br>

        </div>
        <form action="" method="POST">
          {% csrf_token %}
          <div class="form-group">
            <input
              type="text"
              name="subject"
              placeholder="subject"
              id="subjectField"
              
              class="form-control form-control-sm"
            />
          </div>
          <div class="invalid_feedback invalid-feedback" style="display:none">
          </div>
          <p class="text-sm text-success usernameSuccessOutput"></p>
          <div class="form-group">
            <input
              type="email"
              name="email"
              placeholder="Email"
              class="form-control form-control-sm"
              id="emailField"

              value="{{fieldValues.email}}"
            />
          </div>

          <div class="emailFeedBackArea invalid-feedback" style="display:none">
          </div>
          <div class="form-group">
            <input
              type="text"
              name="message"
              placeholder="Message"
              class="form-control form-control-sm"
              id="messageField"
            />
            <small class="float-right py-3 showPasswordToggle">SHOW</small>
          </div>
          <input type="submit" value="Send Message" class="btn btn-block btn-primary submit-btn" /> <br>
        
        <div class="col-md-3 col-md-push-1">
          <h4>Contact Details</h4>
          <ul class="with-icon colored">
            <li><i class="icon-location2"></i> <span>Mudhiraj street, Bhadrachalam 507111</span></li>
            <li><i class="icon-mail"></i><span>{{contact_detail.email}}</span></li>
            <li><i class="icon-phone2"></i><span>{{contact_detail.phone_number}}</span></li>
          </ul>

          
          <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
          <p><a href="#">Learn More</a></p>
        </div>
      </div>
    </div>
  </section>  
  <div id="map"></div>
  {% endif %}
  
  {% endblock body %}
  
  

contact/templates/contact/success.html
<h1>message sent successfully</h1>

demoapp/templates/demoapp/about.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    <div class="jumbotron big-banner" style="height: 500px; padding-top: 150px "></div>
    <br>
    <section class="probootstrap-slider flexslider2 page-inner">
        <div class="overlay"></div>
        <div class="probootstrap-wrap-banner">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
    
                <div class="page-title probootstrap-animate">
                  <div class="probootstrap-breadcrumbs">
                    <a href="{% url 'demoapp:home'%}">Home</a><span>About</span>
                  </div>
                  </section>
    <div class="container">
        <div class="row-5">
            <h2> Mahi tours contact Details </h2>
            <p>Hello folks! it looks like you know us better. Online Tourism gide is auser friendly , easy to use website where tourist can find the complete guidence. visitor can search the place by selecting city and kind of place. no login and registration is required for visitor</p>
        </div>
        <br>
        
            <div class="row">
                <div class="col-md-12">
                        <p> <b>mahesh</b>  </p>
                        <p><b>mahiramavajjala@gmail.com</b>  </p>
                        <p> <b>8978058734 & 9676666750</b> </p>
                </div>
                    
            </div>
            
    </div>
    {% endblock %}
   
</body>
</html>

demoapp/templates/demoapp/detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
    <section class="probootstrap-slider flexslider2 page-inner">
        <div class="overlay"></div>
        <div class="probootstrap-wrap-banner">
          <div class="container">
            <div class="row">
              <div class="col-md-8">
    <div class="page-title probootstrap-animate">
        <div class="probootstrap-breadcrumbs">
          <a href="{% url 'demoapp:tour_package'%}">Tours</a><span>About</span>
        </div>
      </div>
    <div class="row">
        <div class="col-md-2">
            <img class="card" height="250px" src="{{tour.image}}"/>
        </div>
        <div class="col-md-12">
            <h1>{{tour.name}}</h1>
            <h5>{{tour.description}}</h2>
            <p> <b>Rs.{{tour.price}} per person.</b></p>
            
            <a href="{% url 'contact:sendmail'%}">contact for booking details</a>
        </div>
    </div>
    {% endblock %}
</body>
</html>

demoapp/templates/demoapp/home.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  {% block body %}
  <div class="jumbotron big-banner" style="height: 500px; padding-top: 150px "></div>
  

</br>

  <div class="row-5">
    <div class="col-12">
        <h2 style="text-align: center;">About bhadrachalam</h2>
   
      
      <p>Lord Sree Sita Ramachandra Swamy Temple in Bhadrachalam is a Hindu temple of Lord Rama located in Telangana, India. The area is called as Bhadrachalam and is the venue of grand celebrations on Rama Navami day, when the wedding anniversary of Lord Rama and his consort Sita takes place with much fanfare.

          The temple in Bhadrachalam is closely connected with the life of the 17th-century saint composer Kancharla Gopanna who was known as Bhakta Ramadas. Gopanna was the Tahasildar of Bhadrachalam (second half of the 17th century), is said to have used money from the government treasury to build this temple, and was imprisoned in a dungeon at Golconda. Lord Rama is said to have miraculously given the Sultan the money spent by Gopanna, after which he was released. Gopanna then became Bhadrachala Ramadasa and went on to compose innumerable number of songs in Telugu in praise of Rama.
          
          Bhadrachalam and Vijayanagara are sites said to have been closely associated with the Ramayana. Rama, Sita and Lakshmana are said to have stayed at Parnasala, 35 km away from Bhadrachalam. Rama is said to have crossed the river Godavari on his way to Sri Lanka to rescue Sita, at the spot where the Bhadrachalam temple stands, on the northern bank of the river. Legend has it that the son of Meru and Menaka, Bhadra, performed penances towards Rama here. Kabirdas, a Muslim by birth is also closely associated with this temple. It is believed that the images of the deities miraculously disappeared when Kabir was refused entry into the temple and that they reappeared miraculously upon his being permitted to enter.</p>
    </div>
  </div>
</div>
<hr>


  {% endblock %}
  
</body>
</html>

demoapp/templates/demoapp/tours.html
{% extends 'base.html'%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0,shrink-to-fit = no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% block body %}
</br>
        <div class="container">
        
                <h1 style="text-align: center;">Tour packages</h2>
                {% for tour in tours %}
        
                <br>

                <div class="row">
                    <div class="col-6">
                <div class = "card" style = "width:400px;height:400px">
                    <a href="{% url 'demoapp:detail' tour.id %}"><img style="display: list-item;" class = "card-img-top" src = "{{tour.image}}" 
                       alt = "Card Image Center"></a>
                    
                    <div class = "card-body">
                       <h4 class = "card-title">{{tour.name}}</h4>
                       <p class = "card-text">
                    
                        
                        
                       </p>
                       
                    </div>
                 </div>
                </div>
                </div>
                
                
                
    
                
                {% endfor %}
                {% endblock %}
                
               
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'demoapp/style.css' %}">
    
    <title>Bcm tours</title>
    
</head>
<body>
    <nav class="navbar navbar-dark navbar-warning bg-dark">
        <div class="container">
          <a class="navbar-brand" href="{% url 'demoapp:home' %}">Bhadrachalam tours</a>
          
              <div class="navbar">
                <a class="nav-item nav-link" href="{% url 'demoapp:home' %}">Home<span class="sr-only">(current)</span></a>
                <a class="nav-item nav-link" href="{% url 'demoapp:tour_package' %}">Tours</a>
                <a class="nav-item nav-link" href="{% url 'demoapp:contact' %}">About</a>
                <a class="nav-item nav-link" href="{% url 'contact:sendmail' %}">Contact</a>
              </div>
            </div>
        </div>
      </nav>
      {% block body %}
      {% endblock %}
          
      </body>
</html>